/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract/schema.json
export type Button = {
  text?: string;
  url?: string;
  buttonColor?:
    | "brand-gradient"
    | "brand-light"
    | "deep-navy"
    | "outline"
    | "ghost";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Logo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Poster = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "poster.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type UploadedVideoFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: "file";
};

export type UploadedVideoPoster = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "uploadedVideo.poster.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SolutionLogo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "solution.logo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SolutionCardsSection = {
  _type: "solutionCardsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title?: string;
  content?: string;
  solutions: Array<{
    logo?: SolutionLogo;
    name: string;
    title: string;
    content: string;
    button?: Link;
    anchor?: string;
    _type: "solution";
    _key: string;
  }>;
};

export type SolutionDetailsSection = {
  _type: "solutionDetailsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title?: string;
  content?: string;
  items: Array<{
    slug: Slug;
    logo?: Logo;
    title: string;
    subtitle?: string;
    content: string;
    button?: Link;
    capabilitiesTitle?: string;
    capabilities: Array<string>;
    adaptableTitle?: string;
    adaptableItems: Array<string>;
    stack?: Array<string>;
    media?: Array<
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "screenshot";
          _key: string;
        }
      | {
          url: string;
          poster?: Poster;
          alt?: string;
          _type: "video";
          _key: string;
        }
      | {
          file: UploadedVideoFile;
          poster?: UploadedVideoPoster;
          alt?: string;
          _type: "uploadedVideo";
          _key: string;
        }
    >;
    status?: string;
    _type: "solution";
    _key: string;
  }>;
};

export type ValuesSection = {
  _type: "valuesSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content?: string;
  values: Array<{
    icon?: LucideIcon;
    title: string;
    content: string;
    _type: "value";
    _key: string;
  }>;
};

export type FounderSection = {
  _type: "founderSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  name: string;
  role: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quote?: string;
  bio: string;
  links?: Array<{
    platform: "linkedin" | "github" | "x" | "email" | "whatsapp" | "website";
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type StatsSection = {
  _type: "statsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  stats: Array<{
    value: string;
    label: string;
    _type: "stat";
    _key: string;
  }>;
};

export type ContactUsSection = {
  _type: "contactUsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  title: string;
  eyebrow?: string;
  content: string;
  detailsTitle?: string;
  detailsContent?: string;
  formEyebrow?: string;
  contactEmail?: string;
  responseTime?: string;
  whatsappText?: string;
  whatsappUrl?: string;
  highlights?: Array<string>;
};

export type CardsSection = {
  _type: "cardsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  title: string;
  eyebrow?: string;
  content?: string;
  cardItems: Array<{
    icon?: LucideIcon;
    title: string;
    content: string;
    _key: string;
  }>;
};

export type SimpleContentSection = {
  _type: "simpleContentSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  button?: Button;
};

export type ServiceDetailsSection = {
  _type: "serviceDetailsSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  items: Array<{
    title: string;
    content: string;
    tags?: Array<string>;
    includedTitle?: string;
    includedItems: Array<string>;
    outcomesTitle?: string;
    outcomes: Array<string>;
    _type: "service";
    _key: string;
  }>;
};

export type FinalCtaSection = {
  _type: "finalCtaSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  primaryCta?: Link;
  secondaryCta?: Link;
  highlights?: Array<string>;
};

export type ProcessSection = {
  _type: "processSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  deliverableLabel?: string;
  steps: Array<{
    title: string;
    content: string;
    deliverable?: string;
    _type: "processStep";
    _key: string;
  }>;
};

export type CapabilitiesSection = {
  _type: "capabilitiesSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  items: Array<{
    icon?: LucideIcon;
    title: string;
    content: string;
    tags?: Array<string>;
    _type: "capability";
    _key: string;
  }>;
};

export type ProcessHeroSection = {
  _type: "processHeroSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  panelEyebrow?: string;
  steps: Array<{
    title: string;
    content: string;
    _type: "processHeroStep";
    _key: string;
  }>;
};

export type PageSimpleHeroSection = {
  _type: "pageSimpleHeroSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
};

export type PageHeroSection = {
  _type: "pageHeroSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  highlightItems?: Array<{
    title: string;
    icon?: LucideIcon;
    _type: "highlightItem";
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  backgroundColor?:
    | "white"
    | "light-gray"
    | "ice-blue"
    | "sky-blue"
    | "primary"
    | "deep-navy";
  eyebrow?: string;
  title: string;
  content: string;
  primaryCta?: Link;
  secondaryCta?: Link;
  highlights?: Array<{
    title: string;
    _type: "highlight";
    _key: string;
  }>;
  visualEyebrow?: string;
  visualContent?: string;
  visualCards: Array<{
    icon?: LucideIcon;
    title: string;
    content: string;
    _type: "visualCard";
    _key: string;
  }>;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  label?: string;
  page?: PageReference;
  url?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  metaImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type LucideIcon = string;

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | PageReference
    | PostReference
    | CategoryReference
    | SiteSettingsReference;
  language: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  siteName: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: Seo;
  announcementText?: string;
  announcementLink?: Link;
  headerNav?: Array<
    {
      _key: string;
    } & Link
  >;
  headerSecondaryCta?: Link;
  headerPrimaryCta?: Link;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  footerDescription?: string;
  footerPrimaryCta?: Link;
  footerBottomLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  footerMetaText?: string;
  footerBottomText?: string;
  socialLinks?: Array<{
    label?: string;
    icon?: LucideIcon;
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  excerpt?: string;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  parent?: PageReference;
  seo?: Seo;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & PageSimpleHeroSection)
    | ({
        _key: string;
      } & PageHeroSection)
    | ({
        _key: string;
      } & ProcessHeroSection)
    | ({
        _key: string;
      } & CapabilitiesSection)
    | ({
        _key: string;
      } & ProcessSection)
    | ({
        _key: string;
      } & FinalCtaSection)
    | ({
        _key: string;
      } & ServiceDetailsSection)
    | ({
        _key: string;
      } & SimpleContentSection)
    | ({
        _key: string;
      } & CardsSection)
    | ({
        _key: string;
      } & ContactUsSection)
    | ({
        _key: string;
      } & StatsSection)
    | ({
        _key: string;
      } & FounderSection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & SolutionDetailsSection)
    | ({
        _key: string;
      } & SolutionCardsSection)
  >;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Button
  | SanityImageAssetReference
  | Logo
  | Poster
  | SanityFileAssetReference
  | UploadedVideoFile
  | UploadedVideoPoster
  | SolutionLogo
  | SolutionCardsSection
  | SolutionDetailsSection
  | ValuesSection
  | FounderSection
  | StatsSection
  | ContactUsSection
  | CardsSection
  | SimpleContentSection
  | ServiceDetailsSection
  | FinalCtaSection
  | ProcessSection
  | CapabilitiesSection
  | ProcessHeroSection
  | PageSimpleHeroSection
  | PageHeroSection
  | HeroSection
  | PageReference
  | Link
  | Seo
  | LucideIcon
  | BlockContent
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | CategoryReference
  | SiteSettingsReference
  | InternationalizedArrayReferenceValue
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Slug
  | AuthorReference
  | Post
  | Author
  | Page
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_CATEGORY
// Query: *[_type == "category" && language == $language && slug.current == $slug][0]{title,"slug": slug.current,language}
export type BLOG_CATEGORY_RESULT = {
  title: string | null;
  slug: string | null;
  language: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)]{    title,    language,    "slug": slug.current  } | order(title asc)
export type BLOG_CATEGORIES_QUERY_RESULT = Array<{
  title: string | null;
  language: string | null;
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_CATEGORIES_QUERY_LANGUAGE
// Query: *[_type == "category" && language == $language && defined(slug.current)]{    title,    language,    "slug": slug.current  } | order(title asc)
export type BLOG_CATEGORIES_QUERY_LANGUAGE_RESULT = Array<{
  title: string | null;
  language: string | null;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BLOG_CATEGORY_QUERY
// Query: *[_type == "category" && language == $language && slug.current == $slug][0]{    title,    "slug": slug.current,    "posts": *[_type == "post"       && defined(slug.current)       && (!defined(seo.noIndex) || seo.noIndex == false)       && ^._id in categories[]._ref]      | order(coalesce(publishedAt, _createdAt) desc)      [$start...$end]{        _id,        title,        "slug": slug.current,        seo,        body,         excerpt,        mainImage,        language,        "categories": coalesce(          categories[]->{            _id,            slug,            title          },          []        ),        author->{          name,          image        },        relatedPosts[]{          _key,           ...@->{_id, title, slug}        },        publishedAt      },    "total": count(*[_type == "post"       && language == $language      && defined(slug.current)       && (!defined(seo.noIndex) || seo.noIndex == false)       && ^._id in categories[]._ref])  }
export type BLOG_CATEGORY_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    seo: Seo | null;
    body: BlockContent | null;
    excerpt: string | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    language: string | null;
    categories:
      | Array<{
          _id: string;
          slug: Slug | null;
          title: string | null;
        }>
      | Array<never>;
    author: {
      name: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    relatedPosts: Array<{
      _key: string;
      _id: string;
      title: string | null;
      slug: Slug | null;
    }> | null;
    publishedAt: string | null;
  }>;
  total: number;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: {  "posts": *[_type == "post" && language == $language && defined(slug.current) && (!defined(seo.noIndex) || seo.noIndex == false)]    | order(coalesce(publishedAt, _createdAt) desc)    [$start...$end]{      _id,       title,      "slug": slug.current,      seo,      body,       excerpt,      mainImage,      language,      "categories": coalesce(        categories[]->{          _id,          slug,          title        },        []      ),      author->{        name,        image      },      relatedPosts[]{        _key,         ...@->{_id, title, slug}       },      publishedAt    },  "total": count(*[_type == "post" && language == $language && defined(slug.current) && (!defined(seo.noIndex) || seo.noIndex == false)])}
export type POSTS_INDEX_QUERY_RESULT = {
  posts: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    seo: Seo | null;
    body: BlockContent | null;
    excerpt: string | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    language: string | null;
    categories:
      | Array<{
          _id: string;
          slug: Slug | null;
          title: string | null;
        }>
      | Array<never>;
    author: {
      name: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
    relatedPosts: Array<{
      _key: string;
      _id: string;
      title: string | null;
      slug: Slug | null;
    }> | null;
    publishedAt: string | null;
  }>;
  total: number;
};

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)][0...12]{  _id,  title,  "slug": slug.current,  seo,  body,   excerpt,  mainImage,  language,  "categories": coalesce(    categories[]->{      _id,      slug,      title    },    []  ),  author->{    name,    image  },  relatedPosts[]{    _key,     ...@->{_id, title, slug}  },  publishedAt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string;
  seo: Seo | null;
  body: BlockContent | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  language: string | null;
  categories:
    | Array<{
        _id: string;
        slug: Slug | null;
        title: string | null;
      }>
    | Array<never>;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  relatedPosts: Array<{
    _key: string;
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && language == $language && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  seo,  body,   excerpt,  mainImage,  language,  "categories": coalesce(    categories[]->{      _id,      slug,      title    },    []  ),  author->{    name,    image  },  relatedPosts[]{    _key,     ...@->{_id, title, slug}  },  publishedAt}
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  seo: Seo | null;
  body: BlockContent | null;
  excerpt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  language: string | null;
  categories:
    | Array<{
        _id: string;
        slug: Slug | null;
        title: string | null;
      }>
    | Array<never>;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  relatedPosts: Array<{
    _key: string;
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  publishedAt: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    title,    "slug": slug.current,    "parentSlug": parent->slug.current,    seo,    language,    pageBuilder[]{      ...,      _type == "heroSection" => {        primaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        },        secondaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        }      },      _type == "finalCtaSection" => {        primaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        },        secondaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        }      },      _type == "solutionDetailsSection" => {        ...,        items[]{          ...,          button{            label,            url,            "pageSlug": page->slug.current,            "pageParentSlug": page->parent->slug.current,            "pageTitle": page->title,          }        }      },      _type == "solutionCardsSection" => {        ...,        solutions[]{          ...,          button{            label,            url,            "pageSlug": page->slug.current,            "pageParentSlug": page->parent->slug.current,            "pageTitle": page->title,          }        }      }    }  }
export type PAGES_QUERY_RESULT = Array<{
  title: string;
  slug: string;
  parentSlug: string | null;
  seo: Seo | null;
  language: string | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "capabilitiesSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        items: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          tags?: Array<string>;
          _type: "capability";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "cardsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        title: string;
        eyebrow?: string;
        content?: string;
        cardItems: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "contactUsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        title: string;
        eyebrow?: string;
        content: string;
        detailsTitle?: string;
        detailsContent?: string;
        formEyebrow?: string;
        contactEmail?: string;
        responseTime?: string;
        whatsappText?: string;
        whatsappUrl?: string;
        highlights?: Array<string>;
      }
    | {
        _key: string;
        _type: "finalCtaSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        primaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        highlights?: Array<string>;
      }
    | {
        _key: string;
        _type: "founderSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        name: string;
        role: string;
        photo?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        quote?: string;
        bio: string;
        links?: Array<{
          platform:
            | "email"
            | "github"
            | "linkedin"
            | "website"
            | "whatsapp"
            | "x";
          url: string;
          _type: "socialLink";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        primaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        highlights?: Array<{
          title: string;
          _type: "highlight";
          _key: string;
        }>;
        visualEyebrow?: string;
        visualContent?: string;
        visualCards: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _type: "visualCard";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "pageHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        highlightItems?: Array<{
          title: string;
          icon?: LucideIcon;
          _type: "highlightItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "pageSimpleHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
      }
    | {
        _key: string;
        _type: "processHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        panelEyebrow?: string;
        steps: Array<{
          title: string;
          content: string;
          _type: "processHeroStep";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "processSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        deliverableLabel?: string;
        steps: Array<{
          title: string;
          content: string;
          deliverable?: string;
          _type: "processStep";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "serviceDetailsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        items: Array<{
          title: string;
          content: string;
          tags?: Array<string>;
          includedTitle?: string;
          includedItems: Array<string>;
          outcomesTitle?: string;
          outcomes: Array<string>;
          _type: "service";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "simpleContentSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        button?: Button;
      }
    | {
        _key: string;
        _type: "solutionCardsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title?: string;
        content?: string;
        solutions: Array<{
          logo?: SolutionLogo;
          name: string;
          title: string;
          content: string;
          button: {
            label: string | null;
            url: string | null;
            pageSlug: string | null;
            pageParentSlug: string | null;
            pageTitle: string | null;
          } | null;
          anchor?: string;
          _type: "solution";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "solutionDetailsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title?: string;
        content?: string;
        items: Array<{
          slug: Slug;
          logo?: Logo;
          title: string;
          subtitle?: string;
          content: string;
          button: {
            label: string | null;
            url: string | null;
            pageSlug: string | null;
            pageParentSlug: string | null;
            pageTitle: string | null;
          } | null;
          capabilitiesTitle?: string;
          capabilities: Array<string>;
          adaptableTitle?: string;
          adaptableItems: Array<string>;
          stack?: Array<string>;
          media?: Array<
            | {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                _type: "screenshot";
                _key: string;
              }
            | {
                file: UploadedVideoFile;
                poster?: UploadedVideoPoster;
                alt?: string;
                _type: "uploadedVideo";
                _key: string;
              }
            | {
                url: string;
                poster?: Poster;
                alt?: string;
                _type: "video";
                _key: string;
              }
          >;
          status?: string;
          _type: "solution";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "statsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        stats: Array<{
          value: string;
          label: string;
          _type: "stat";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "valuesSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content?: string;
        values: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _type: "value";
          _key: string;
        }>;
      }
  > | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && language == $language && slug.current == $slug][0]{    title,    "slug": slug.current,    "parentSlug": parent->slug.current,    seo,    language,    pageBuilder[]{      ...,      _type == "heroSection" => {        primaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        },        secondaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        }      },      _type == "finalCtaSection" => {        primaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        },        secondaryCta{          label,          url,          "pageSlug": page->slug.current,          "pageParentSlug": page->parent->slug.current,          "pageTitle": page->title,        }      },      _type == "solutionDetailsSection" => {        ...,        items[]{          ...,          button{            label,            url,            "pageSlug": page->slug.current,            "pageParentSlug": page->parent->slug.current,            "pageTitle": page->title,          }        }      },      _type == "solutionCardsSection" => {        ...,        solutions[]{          ...,          button{            label,            url,            "pageSlug": page->slug.current,            "pageParentSlug": page->parent->slug.current,            "pageTitle": page->title,          }        }      }    }  }
export type PAGE_QUERY_RESULT = {
  title: string;
  slug: string;
  parentSlug: string | null;
  seo: Seo | null;
  language: string | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "capabilitiesSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        items: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          tags?: Array<string>;
          _type: "capability";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "cardsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        title: string;
        eyebrow?: string;
        content?: string;
        cardItems: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "contactUsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        title: string;
        eyebrow?: string;
        content: string;
        detailsTitle?: string;
        detailsContent?: string;
        formEyebrow?: string;
        contactEmail?: string;
        responseTime?: string;
        whatsappText?: string;
        whatsappUrl?: string;
        highlights?: Array<string>;
      }
    | {
        _key: string;
        _type: "finalCtaSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        primaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        highlights?: Array<string>;
      }
    | {
        _key: string;
        _type: "founderSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        name: string;
        role: string;
        photo?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        quote?: string;
        bio: string;
        links?: Array<{
          platform:
            | "email"
            | "github"
            | "linkedin"
            | "website"
            | "whatsapp"
            | "x";
          url: string;
          _type: "socialLink";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        primaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          url: string | null;
          pageSlug: string | null;
          pageParentSlug: string | null;
          pageTitle: string | null;
        } | null;
        highlights?: Array<{
          title: string;
          _type: "highlight";
          _key: string;
        }>;
        visualEyebrow?: string;
        visualContent?: string;
        visualCards: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _type: "visualCard";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "pageHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        highlightItems?: Array<{
          title: string;
          icon?: LucideIcon;
          _type: "highlightItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "pageSimpleHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
      }
    | {
        _key: string;
        _type: "processHeroSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        panelEyebrow?: string;
        steps: Array<{
          title: string;
          content: string;
          _type: "processHeroStep";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "processSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        deliverableLabel?: string;
        steps: Array<{
          title: string;
          content: string;
          deliverable?: string;
          _type: "processStep";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "serviceDetailsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        items: Array<{
          title: string;
          content: string;
          tags?: Array<string>;
          includedTitle?: string;
          includedItems: Array<string>;
          outcomesTitle?: string;
          outcomes: Array<string>;
          _type: "service";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "simpleContentSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        button?: Button;
      }
    | {
        _key: string;
        _type: "solutionCardsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title?: string;
        content?: string;
        solutions: Array<{
          logo?: SolutionLogo;
          name: string;
          title: string;
          content: string;
          button: {
            label: string | null;
            url: string | null;
            pageSlug: string | null;
            pageParentSlug: string | null;
            pageTitle: string | null;
          } | null;
          anchor?: string;
          _type: "solution";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "solutionDetailsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title?: string;
        content?: string;
        items: Array<{
          slug: Slug;
          logo?: Logo;
          title: string;
          subtitle?: string;
          content: string;
          button: {
            label: string | null;
            url: string | null;
            pageSlug: string | null;
            pageParentSlug: string | null;
            pageTitle: string | null;
          } | null;
          capabilitiesTitle?: string;
          capabilities: Array<string>;
          adaptableTitle?: string;
          adaptableItems: Array<string>;
          stack?: Array<string>;
          media?: Array<
            | {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt?: string;
                _type: "screenshot";
                _key: string;
              }
            | {
                file: UploadedVideoFile;
                poster?: UploadedVideoPoster;
                alt?: string;
                _type: "uploadedVideo";
                _key: string;
              }
            | {
                url: string;
                poster?: Poster;
                alt?: string;
                _type: "video";
                _key: string;
              }
          >;
          status?: string;
          _type: "solution";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "statsSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content: string;
        stats: Array<{
          value: string;
          label: string;
          _type: "stat";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "valuesSection";
        backgroundColor?:
          | "deep-navy"
          | "ice-blue"
          | "light-gray"
          | "primary"
          | "sky-blue"
          | "white";
        eyebrow?: string;
        title: string;
        content?: string;
        values: Array<{
          icon?: LucideIcon;
          title: string;
          content: string;
          _type: "value";
          _key: string;
        }>;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && language == $language][0]{    siteName,    logo,    logoDark,    seo,    announcementText,    announcementLink{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    headerNav[]{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    headerSecondaryCta{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    headerPrimaryCta{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    footerColumns[]{      title,      links[]{        label,        url,        "pageSlug": page->slug.current,        "pageParentSlug": page->parent->slug.current,        "pageTitle": page->title,      }    },    footerDescription,    footerPrimaryCta{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    footerBottomLinks[]{      label,      url,      "pageSlug": page->slug.current,      "pageParentSlug": page->parent->slug.current,      "pageTitle": page->title,    },    footerMetaText,    footerBottomText,    socialLinks[]  }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seo: Seo | null;
  announcementText: string | null;
  announcementLink: {
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  } | null;
  headerNav: Array<{
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  }> | null;
  headerSecondaryCta: {
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  } | null;
  headerPrimaryCta: {
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  } | null;
  footerColumns: Array<{
    title: string | null;
    links: Array<{
      label: string | null;
      url: string | null;
      pageSlug: string | null;
      pageParentSlug: string | null;
      pageTitle: string | null;
    }> | null;
  }> | null;
  footerDescription: string | null;
  footerPrimaryCta: {
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  } | null;
  footerBottomLinks: Array<{
    label: string | null;
    url: string | null;
    pageSlug: string | null;
    pageParentSlug: string | null;
    pageTitle: string | null;
  }> | null;
  footerMetaText: string | null;
  footerBottomText: string | null;
  socialLinks: Array<{
    label?: string;
    icon?: LucideIcon;
    url: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITEMAP_QUERY
// Query: {  "pages": *[    _type == "page"    && defined(slug.current)    && (!defined(seo.noIndex) || seo.noIndex == false)  ]{    _id,    "slug": slug.current,    "parentSlug": parent->slug.current,    language,    _updatedAt  },  "posts": *[    _type == "post"    && defined(slug.current)    && (!defined(seo.noIndex) || seo.noIndex == false)  ]{    _id,    "slug": slug.current,    language,    _updatedAt  },  "categories": *[    _type == "category"    && defined(slug.current)  ]{    _id,    language,    "slug": slug.current  },  "translations": *[_type == "translation.metadata"]{    translations[]{      _key,      language,      "ref": value._ref    }  }}
export type SITEMAP_QUERY_RESULT = {
  pages: Array<{
    _id: string;
    slug: string;
    parentSlug: string | null;
    language: string | null;
    _updatedAt: string;
  }>;
  posts: Array<{
    _id: string;
    slug: string | null;
    language: string | null;
    _updatedAt: string;
  }>;
  categories: Array<{
    _id: string;
    language: string | null;
    slug: string;
  }>;
  translations: Array<{
    translations: Array<{
      _key: string;
      language: string;
      ref: string | null;
    }> | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "category" && language == $language && slug.current == $slug][0]{title,"slug": slug.current,language}': BLOG_CATEGORY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)]{\n    title,\n    language,\n    "slug": slug.current\n  } | order(title asc)\n': BLOG_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && language == $language && defined(slug.current)]{\n    title,\n    language,\n    "slug": slug.current\n  } | order(title asc)\n': BLOG_CATEGORIES_QUERY_LANGUAGE_RESULT;
    '\n  *[_type == "category" && language == $language && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    "posts": *[_type == "post" \n      && defined(slug.current) \n      && (!defined(seo.noIndex) || seo.noIndex == false) \n      && ^._id in categories[]._ref]\n      | order(coalesce(publishedAt, _createdAt) desc)\n      [$start...$end]{\n        _id,\n        title,\n        "slug": slug.current,\n        seo,\n        body, \n        excerpt,\n        mainImage,\n        language,\n        "categories": coalesce(\n          categories[]->{\n            _id,\n            slug,\n            title\n          },\n          []\n        ),\n        author->{\n          name,\n          image\n        },\n        relatedPosts[]{\n          _key, \n          ...@->{_id, title, slug}\n        },\n        publishedAt\n      },\n    "total": count(*[_type == "post" \n      && language == $language\n      && defined(slug.current) \n      && (!defined(seo.noIndex) || seo.noIndex == false) \n      && ^._id in categories[]._ref])\n  }\n': BLOG_CATEGORY_QUERY_RESULT;
    '\n{\n  "posts": *[_type == "post" && language == $language && defined(slug.current) && (!defined(seo.noIndex) || seo.noIndex == false)]\n    | order(coalesce(publishedAt, _createdAt) desc)\n    [$start...$end]{\n      _id, \n      title,\n      "slug": slug.current,\n      seo,\n      body, \n      excerpt,\n      mainImage,\n      language,\n      "categories": coalesce(\n        categories[]->{\n          _id,\n          slug,\n          title\n        },\n        []\n      ),\n      author->{\n        name,\n        image\n      },\n      relatedPosts[]{\n        _key, \n        ...@->{_id, title, slug} \n      },\n      publishedAt\n    },\n  "total": count(*[_type == "post" && language == $language && defined(slug.current) && (!defined(seo.noIndex) || seo.noIndex == false)])\n}\n': POSTS_INDEX_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)][0...12]{\n  _id,\n  title,\n  "slug": slug.current,\n  seo,\n  body, \n  excerpt,\n  mainImage,\n  language,\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      slug,\n      title\n    },\n    []\n  ),\n  author->{\n    name,\n    image\n  },\n  relatedPosts[]{\n    _key, \n    ...@->{_id, title, slug}\n  },\n  publishedAt\n}': POSTS_QUERY_RESULT;
    '*[_type == "post" && language == $language && slug.current == $slug][0]{\n  _id,\n  title,\n  "slug": slug.current,\n  seo,\n  body, \n  excerpt,\n  mainImage,\n  language,\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      slug,\n      title\n    },\n    []\n  ),\n  author->{\n    name,\n    image\n  },\n  relatedPosts[]{\n    _key, \n    ...@->{_id, title, slug}\n  },\n  publishedAt\n}': POST_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{\n    title,\n    "slug": slug.current,\n    "parentSlug": parent->slug.current,\n    seo,\n    language,\n    pageBuilder[]{\n      ...,\n      _type == "heroSection" => {\n        primaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        },\n        secondaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        }\n      },\n      _type == "finalCtaSection" => {\n        primaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        },\n        secondaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        }\n      },\n      _type == "solutionDetailsSection" => {\n        ...,\n        items[]{\n          ...,\n          button{\n            label,\n            url,\n            "pageSlug": page->slug.current,\n            "pageParentSlug": page->parent->slug.current,\n            "pageTitle": page->title,\n          }\n        }\n      },\n      _type == "solutionCardsSection" => {\n        ...,\n        solutions[]{\n          ...,\n          button{\n            label,\n            url,\n            "pageSlug": page->slug.current,\n            "pageParentSlug": page->parent->slug.current,\n            "pageTitle": page->title,\n          }\n        }\n      }\n    }\n  }': PAGES_QUERY_RESULT;
    '*[_type == "page" && language == $language && slug.current == $slug][0]{\n    title,\n    "slug": slug.current,\n    "parentSlug": parent->slug.current,\n    seo,\n    language,\n    pageBuilder[]{\n      ...,\n      _type == "heroSection" => {\n        primaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        },\n        secondaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        }\n      },\n      _type == "finalCtaSection" => {\n        primaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        },\n        secondaryCta{\n          label,\n          url,\n          "pageSlug": page->slug.current,\n          "pageParentSlug": page->parent->slug.current,\n          "pageTitle": page->title,\n        }\n      },\n      _type == "solutionDetailsSection" => {\n        ...,\n        items[]{\n          ...,\n          button{\n            label,\n            url,\n            "pageSlug": page->slug.current,\n            "pageParentSlug": page->parent->slug.current,\n            "pageTitle": page->title,\n          }\n        }\n      },\n      _type == "solutionCardsSection" => {\n        ...,\n        solutions[]{\n          ...,\n          button{\n            label,\n            url,\n            "pageSlug": page->slug.current,\n            "pageParentSlug": page->parent->slug.current,\n            "pageTitle": page->title,\n          }\n        }\n      }\n    }\n  }': PAGE_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && language == $language][0]{\n    siteName,\n    logo,\n    logoDark,\n    seo,\n    announcementText,\n    announcementLink{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    headerNav[]{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    headerSecondaryCta{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    headerPrimaryCta{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    footerColumns[]{\n      title,\n      links[]{\n        label,\n        url,\n        "pageSlug": page->slug.current,\n        "pageParentSlug": page->parent->slug.current,\n        "pageTitle": page->title,\n      }\n    },\n    footerDescription,\n    footerPrimaryCta{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    footerBottomLinks[]{\n      label,\n      url,\n      "pageSlug": page->slug.current,\n      "pageParentSlug": page->parent->slug.current,\n      "pageTitle": page->title,\n    },\n    footerMetaText,\n    footerBottomText,\n    socialLinks[]\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n{\n  "pages": *[\n    _type == "page"\n    && defined(slug.current)\n    && (!defined(seo.noIndex) || seo.noIndex == false)\n  ]{\n    _id,\n    "slug": slug.current,\n    "parentSlug": parent->slug.current,\n    language,\n    _updatedAt\n  },\n\n  "posts": *[\n    _type == "post"\n    && defined(slug.current)\n    && (!defined(seo.noIndex) || seo.noIndex == false)\n  ]{\n    _id,\n    "slug": slug.current,\n    language,\n    _updatedAt\n  },\n\n  "categories": *[\n    _type == "category"\n    && defined(slug.current)\n  ]{\n    _id,\n    language,\n    "slug": slug.current\n  },\n\n  "translations": *[_type == "translation.metadata"]{\n    translations[]{\n      _key,\n      language,\n      "ref": value._ref\n    }\n  }\n}\n': SITEMAP_QUERY_RESULT;
  }
}
